# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('read_mount', models.IntegerField(default=0)),
                ('commit_mount', models.IntegerField(default=0)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.ArticleCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField()),
                ('commit_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('commit_display', models.IntegerField(default=1)),
                ('floor', models.IntegerField(default=0, null=True)),
                ('commit_artcles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Commit2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit2', models.TextField()),
                ('commit2_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('commit2_display', models.IntegerField(default=1)),
                ('commit2_artcles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit2_artcles_back', to='weibo.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Fllows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserSex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.UserLocation'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.UserSex'),
        ),
        migrations.AddField(
            model_name='fllows',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_to_fllows', to='weibo.UserInfo'),
        ),
        migrations.AddField(
            model_name='fllows',
            name='fllow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fllow_to_author', to='weibo.UserInfo'),
        ),
        migrations.AddField(
            model_name='commit2',
            name='commit2_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit2_author_back', to='weibo.UserInfo'),
        ),
        migrations.AddField(
            model_name='commit2',
            name='commit2_to_commit1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit2_to_commit1_back', to='weibo.Commit'),
        ),
        migrations.AddField(
            model_name='commit2',
            name='commit2_to_self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit2_to_self_back', to='weibo.Commit2'),
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.UserInfo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.UserLocation'),
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='fllows',
            unique_together=set([('author_id', 'fllow_id')]),
        ),
    ]
