# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('floor', 'commit_artcles')]),
        ),
    ]
